<?xml version="1.0" encoding="utf-8"?><Database Name="DbStudent" Class="LINQdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=XOAPIT\SQLEXPRESS;Initial Catalog=DbStudent;Integrated Security=True" SettingsObjectName="QuanLySinhVien3.Properties.Settings" SettingsPropertyName="DbStudentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LOP" Member="LOPs">
    <Type Name="LOP">
      <Column Name="ID_Class" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ten_Class" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SINHVIEN" Member="SINHVIENs">
    <Type Name="SINHVIEN">
      <Column Name="MSSV" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Class" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.updateSV" Method="updateSV">
    <Parameter Name="mssv" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="birthday" Type="System.DateTime" DbType="Date" />
    <Parameter Name="gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="address" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mobile" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="id_class" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertSV" Method="insertSV">
    <Parameter Name="mssv" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="birthday" Type="System.DateTime" DbType="Date" />
    <Parameter Name="gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="address" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mobile" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="id_class" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getListSV" Method="getListSV">
    <ElementType Name="getListSVResult">
      <Column Name="MSSV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Class" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getListLOP" Method="getListLOP">
    <ElementType Name="getListLOPResult">
      <Column Name="ID_Class" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ten_Class" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>