//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbDotNetEntities : DbContext
    {
        public dbDotNetEntities()
            : base("name=dbDotNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KHOA> KHOAs { get; set; }
        public DbSet<LOP> LOPs { get; set; }
        public DbSet<SINHVIEN> SINHVIENs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int getCountSV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getCountSV");
        }
    }
}
