//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string MaSo { get; set; }
        public string HoTen { get; set; }
        public string Id_lop { get; set; }
        public string NienKhoa { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
    
        public virtual LOP LOP { get; set; }
    }
}
